# Generated by Django 2.2.13 on 2021-01-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_event_use_contact_tracing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="photo_consent",
            new_name="LEGACY_photo_consent",
        ),
    ]
