# Generated by Django 2.2.13 on 2021-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_phone_number"),
        ("events", "0030_auto_20210207_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="groups_with_view_permission",
            field=models.ManyToManyField(blank=True, to="users.AbakusGroup"),
        ),
    ]
