# Generated by Django 2.2.13 on 2021-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_auto_20210207_1637"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="can_view_groups",
            field=models.ManyToManyField(blank=True, to="users.AbakusGroup"),
        ),
    ]
